/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as CheckEmailRouteImport } from './routes/check-email'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoverRouteImport } from './routes/recover'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppCvsRouteImport } from './routes/app.cvs'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppJobsRouteImport } from './routes/app.jobs'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as RecoverConfirmRouteImport } from './routes/recover_.confirm'
import { Route as AppCvsIndexRouteImport } from './routes/app.cvs.index'
import { Route as AppCvsCvIdRouteImport } from './routes/app.cvs.$cvId'
import { Route as AppCvsNewRouteImport } from './routes/app.cvs.new'
import { Route as AppJobsIndexRouteImport } from './routes/app.jobs.index'
import { Route as AppJobsJobIdRouteImport } from './routes/app.jobs.$jobId'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckEmailRoute = CheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRoute = RecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCvsRoute = AppCvsRouteImport.update({
  id: '/cvs',
  path: '/cvs',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverConfirmRoute = RecoverConfirmRouteImport.update({
  id: '/recover_/confirm',
  path: '/recover/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCvsIndexRoute = AppCvsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCvsRoute,
} as any)
const AppCvsCvIdRoute = AppCvsCvIdRouteImport.update({
  id: '/$cvId',
  path: '/$cvId',
  getParentRoute: () => AppCvsRoute,
} as any)
const AppCvsNewRoute = AppCvsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppCvsRoute,
} as any)
const AppJobsIndexRoute = AppJobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppJobsRoute,
} as any)
const AppJobsJobIdRoute = AppJobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => AppJobsRoute,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/check-email': typeof CheckEmailRoute
  '/login': typeof LoginRoute
  '/recover': typeof RecoverRoute
  '/signup': typeof SignupRoute
  '/app/cvs': typeof AppCvsRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/jobs': typeof AppJobsRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/recover/confirm': typeof RecoverConfirmRoute
  '/app/cvs/$cvId': typeof AppCvsCvIdRoute
  '/app/cvs/new': typeof AppCvsNewRoute
  '/app/jobs/$jobId': typeof AppJobsJobIdRoute
  '/app/cvs/': typeof AppCvsIndexRoute
  '/app/jobs/': typeof AppJobsIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/check-email': typeof CheckEmailRoute
  '/login': typeof LoginRoute
  '/recover': typeof RecoverRoute
  '/signup': typeof SignupRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/recover/confirm': typeof RecoverConfirmRoute
  '/app/cvs/$cvId': typeof AppCvsCvIdRoute
  '/app/cvs/new': typeof AppCvsNewRoute
  '/app/jobs/$jobId': typeof AppJobsJobIdRoute
  '/app/cvs': typeof AppCvsIndexRoute
  '/app/jobs': typeof AppJobsIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/check-email': typeof CheckEmailRoute
  '/login': typeof LoginRoute
  '/recover': typeof RecoverRoute
  '/signup': typeof SignupRoute
  '/app/cvs': typeof AppCvsRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/jobs': typeof AppJobsRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/recover_/confirm': typeof RecoverConfirmRoute
  '/app/cvs/$cvId': typeof AppCvsCvIdRoute
  '/app/cvs/new': typeof AppCvsNewRoute
  '/app/jobs/$jobId': typeof AppJobsJobIdRoute
  '/app/cvs/': typeof AppCvsIndexRoute
  '/app/jobs/': typeof AppJobsIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/check-email'
    | '/login'
    | '/recover'
    | '/signup'
    | '/app/cvs'
    | '/app/dashboard'
    | '/app/jobs'
    | '/app/profile'
    | '/app/settings'
    | '/auth/callback'
    | '/recover/confirm'
    | '/app/cvs/$cvId'
    | '/app/cvs/new'
    | '/app/jobs/$jobId'
    | '/app/cvs/'
    | '/app/jobs/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/check-email'
    | '/login'
    | '/recover'
    | '/signup'
    | '/app/dashboard'
    | '/app/profile'
    | '/app/settings'
    | '/auth/callback'
    | '/recover/confirm'
    | '/app/cvs/$cvId'
    | '/app/cvs/new'
    | '/app/jobs/$jobId'
    | '/app/cvs'
    | '/app/jobs'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/check-email'
    | '/login'
    | '/recover'
    | '/signup'
    | '/app/cvs'
    | '/app/dashboard'
    | '/app/jobs'
    | '/app/profile'
    | '/app/settings'
    | '/auth/callback'
    | '/recover_/confirm'
    | '/app/cvs/$cvId'
    | '/app/cvs/new'
    | '/app/jobs/$jobId'
    | '/app/cvs/'
    | '/app/jobs/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CheckEmailRoute: typeof CheckEmailRoute
  LoginRoute: typeof LoginRoute
  RecoverRoute: typeof RecoverRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  RecoverConfirmRoute: typeof RecoverConfirmRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-email': {
      id: '/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof CheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/cvs': {
      id: '/app/cvs'
      path: '/cvs'
      fullPath: '/app/cvs'
      preLoaderRoute: typeof AppCvsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jobs': {
      id: '/app/jobs'
      path: '/jobs'
      fullPath: '/app/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover_/confirm': {
      id: '/recover_/confirm'
      path: '/recover/confirm'
      fullPath: '/recover/confirm'
      preLoaderRoute: typeof RecoverConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/cvs/': {
      id: '/app/cvs/'
      path: '/'
      fullPath: '/app/cvs/'
      preLoaderRoute: typeof AppCvsIndexRouteImport
      parentRoute: typeof AppCvsRoute
    }
    '/app/cvs/$cvId': {
      id: '/app/cvs/$cvId'
      path: '/$cvId'
      fullPath: '/app/cvs/$cvId'
      preLoaderRoute: typeof AppCvsCvIdRouteImport
      parentRoute: typeof AppCvsRoute
    }
    '/app/cvs/new': {
      id: '/app/cvs/new'
      path: '/new'
      fullPath: '/app/cvs/new'
      preLoaderRoute: typeof AppCvsNewRouteImport
      parentRoute: typeof AppCvsRoute
    }
    '/app/jobs/': {
      id: '/app/jobs/'
      path: '/'
      fullPath: '/app/jobs/'
      preLoaderRoute: typeof AppJobsIndexRouteImport
      parentRoute: typeof AppJobsRoute
    }
    '/app/jobs/$jobId': {
      id: '/app/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/app/jobs/$jobId'
      preLoaderRoute: typeof AppJobsJobIdRouteImport
      parentRoute: typeof AppJobsRoute
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppCvsRouteChildren {
  AppCvsCvIdRoute: typeof AppCvsCvIdRoute
  AppCvsNewRoute: typeof AppCvsNewRoute
  AppCvsIndexRoute: typeof AppCvsIndexRoute
}

const AppCvsRouteChildren: AppCvsRouteChildren = {
  AppCvsCvIdRoute: AppCvsCvIdRoute,
  AppCvsNewRoute: AppCvsNewRoute,
  AppCvsIndexRoute: AppCvsIndexRoute,
}

const AppCvsRouteWithChildren =
  AppCvsRoute._addFileChildren(AppCvsRouteChildren)

interface AppJobsRouteChildren {
  AppJobsJobIdRoute: typeof AppJobsJobIdRoute
  AppJobsIndexRoute: typeof AppJobsIndexRoute
}

const AppJobsRouteChildren: AppJobsRouteChildren = {
  AppJobsJobIdRoute: AppJobsJobIdRoute,
  AppJobsIndexRoute: AppJobsIndexRoute,
}

const AppJobsRouteWithChildren =
  AppJobsRoute._addFileChildren(AppJobsRouteChildren)

interface AppRouteChildren {
  AppCvsRoute: typeof AppCvsRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppJobsRoute: typeof AppJobsRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCvsRoute: AppCvsRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppJobsRoute: AppJobsRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CheckEmailRoute: CheckEmailRoute,
  LoginRoute: LoginRoute,
  RecoverRoute: RecoverRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  RecoverConfirmRoute: RecoverConfirmRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
